[package]
name = "zerotier-protocol"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
description = "ZeroTier V1 wire format types and protocol definitions"

[dependencies]
zerotier-crypto = { workspace = true }
zerocopy = { workspace = true }
thiserror = { workspace = true }
hashbrown = { workspace = true }
